AIRPLANE_MIN_ID: int = 2
AIRPLANE_MAX_ID: int = 999
FUEL_TANK_CAPACITY_MULTIPLIER: int = 200
AIRPLANE_FUEL_CONSUMPTION_MULTIPLIER: float = 0.80
PER_PASSENGER_FUEL_CONSUMPTION_MULTIPLIER: float = 0.002
