AIRPLANE_MIN_ID: int = 1
AIRPLANE_MAX_ID: int = 9999
DEFAULT_NUMBER_OF_PASSENGERS: int = 0
FUEL_TANK_CAPACITY_MULTIPLIER: int = 200
AIRPLANE_FUEL_CONSUMPTION_MULTIPLIER: float = 0.80
PER_PASSENGER_FUEL_CONSUMPTION_MULTIPLIER: float = 0.002
